#
spring:
  datasource:
    druid:
      initial-size: @db.initial-size@
      max-active: @db.max-active@
      min-idle: @db.min-idle@
      max-wait: @db.max-wait@
      pool-prepared-statements: false
      max-open-prepared-statements: 0
      validation-query: SELECT 'X'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      default-datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: @db.url@
        username: @db.username@
        password: @db.password@
        initial-size: @db.initial-size@
        max-active: @db.max-active@
        max-wait: @db.max-wait@
  jackson:
    default-property-inclusion: non_null
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  restpool:
    max-total: @max.total@
    max-per-router: @max.per.router@
    socket-time-out: @socket.time.out@
    connection-time-out: @connection.time.out@
    connection-request-time-out: @connection.request.time.out@
    ignorssl: @ignorssl@
  redis:
    host: @redis.host@
    port: @redis.port@
    password: @redis.password@
    pool:
      max-active: 16
      max-idle: 16
      max-wait: -1
      min-idle: 0
  threadpool:
    core-pool-size: @spring.core-pool-size@
    max-pool-size: @spring.max-pool-size@
    queue-capacity: @spring.queue-capacity@
    keep-alive-seconds: @spring.keep-alive-seconds@
  http:
    multipart:
      max-file-size: 3MB
server:
  port: @server.port@
  connection-timeout: 40000
  context-path: /usercenter
  tomcat:
    basedir: @bjca.log.dir@/tomcat
    background-processor-delay: 30
    max-http-post-size: 10000000
    accesslog:
      enabled: true
      buffered: true
      directory: ./log
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D'
      prefix: access_log
      suffix: .log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
swagger:
  title: bjca-usercenter
  description: Starter for swagger 2.x
  version: ${project.version}
authcode:
  app-id: @authcode.appId@
  template-id: @authcode.templateId@
  sign-algo: @authcode.signAlgo@
  sign-key: @authcode.signKey@
  codeUrl: @authcode.codeUrl@
  emailUrl: @authcode.emailUrl@
  emailBody: "亲爱的%s用户您好,\n验证码：%s,5分钟内输入有效,请输入验证码完成%s,勿将验证码告诉其他人."
  validateUrl: @authcode.validateUrl@
  version: @authcode.version@
  expire: @authcode.expire@
  deviceId: @authcode.deviceId@
  fromName: @authcode.fromName@
  develop-id: "@msg-develop-id@"
  develop-key: "@msg-develop-key@"
idservice:
  user-name: @idservice.userName@
  password: @idservice.password@
  ent-base: @idservice.ent.base@
  ent-pay-verify: @idservice.ent.payVerify@
  ent-pay-verify-query: @idservice.ent.payVerifyQuery@
usercenter:
  username: ${idservice.userName}
  password: ${idservice.password}
  bank4: @bank4.url@
account:
  login:
    max-attempts: @max-attempts@
    attempts-duration-minutes: @attempts-duration-minutes@
    locked-expire-minutes: @locked-expire-minutes@
    token-expire-minutes: @token-expire-minutes@
signService:
  verifySign-url: @verifySign.url@
  parseCertUid-url: @parseCertUid.url@
images:
  download-url: @bedrock-oss.download.url@
  upload-url: @bedrock-oss.upload.url@